services:
  openldap:
    image: bitnami/openldap:2.6
    environment:
      LDAP_ROOT: dc=example,dc=org
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: admin
      LDAP_USERS: ""
      LDAP_PASSWORDS: ""
      LDAP_PORT_NUMBER: "1389"
    ports:
      - "389:1389"
      - "636:1636"
    volumes:
      - ldap_data:/bitnami/openldap

volumes:
  ldap_data:
